---
apiVersion: v1
kind: Service
metadata:
  name: my-grafana-package 
  namespace: new-app 
spec:
  selector:
    app: nginx
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: grafana
  type: NodePort
