apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx 
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes: 
      - name: nginx-vol
        persistentVolumeClaim:
         claimName: nginx-vol
      containers:
      - name: nginx
        image: nginx:1.9
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: nginx-vol
            mountPath: /usr/share/nginx/html

