---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment 
  namespace: ##YOUR-NAMESPACE## 
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort