---
apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod 
   namespace: name1
spec:
 containers:
      - name: nginx
        image: nginx:1.7
        ports:
        - name: http
          containerPort: 80
