apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-vol
  namespace: ##EDIT-NAMESPACE##
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ontap
